<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "easyvote_location"
 *
 * Auto generated by Extension Builder 2015-02-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Display possible voting locations on a map',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Fabien Udriot',
	'author_email' => 'fabien@udriot.net',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0-dev',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);